### ISSUE TITLE
PROXIES not defined

### ISSUE THREAD

**Issue by nickcanarelli** [theriley106/SneakerBotTutorials#10]
Hi all,

Just installed the sneakerbot, however im receiving the following error immediately following running the 'python app.py' command in terminal. 

Haven't really messed around with it, looking for a quick solution if possible.

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/developer/Desktop/SneakerBot/SneakerBotTutorials/app.py", line 132, in index
    info = massTestProxies(PROXIES)
NameError: global name 'PROXIES' is not defined
```

**Comment by GravyPouch** [comment]
same

**Comment by nickcanarelli** [comment]
Its fixed with the new app.py update (12/07/2017). In terminal, navigate to SneakerBotTutorials folder, run:
`git pull`

Should be fine from here on out. Thank you again Chris.
