### ISSUE TITLE
Ran testingCookies.py, but it's not working.

### ISSUE THREAD

**Issue by nickcanarelli** [theriley106/SneakerBotTutorials#13]
`Traceback (most recent call last):
  File "testingCookies.py", line 32, in <module>
    new = convertHeadless(driver, 'https://www.amazon.com/gp/cart/view.html/ref=nav_cart')
  File "testingCookies.py", line 17, in convertHeadless
    driver = webdriver.Firefox()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/97/bfdl_fwn65nf6z35426y91s40000gp/T/tmp3EknVq If you specified a log_file in the FirefoxBinary constructor, check it for details.
`

Any ideas where i might have gone wrong?

**Comment by theriley106** [comment]
It looks like you don't have the Mozilla webdriver installed.

Checkout [this StackOverflow post](https://stackoverflow.com/questions/42204897/how-to-setup-selenium-python-environment-for-firefox)

**Comment by nickcanarelli** [comment]
I'm still getting this error:

`Traceback (most recent call last):
  File "testingCookies.py", line 32, in <module>
    new = convertHeadless(driver, 'https://www.amazon.com/gp/cart/view.html/ref=nav_cart')
  File "testingCookies.py", line 17, in convertHeadless
    driver = webdriver.Firefox(executable_path='/Users/developer/Downloads/geckodriver.exe')
  File "/Users/developer/Desktop/SneakerBot/venv/yeezy/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    self.service.start()
  File "/Users/developer/Desktop/SneakerBot/venv/yeezy/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver.exe' executable needs to be in PATH. `

**Comment by thebotsmith** [comment]
what do you not get? it is telling you there error here " 'geckodriver.exe' executable needs to be in PATH."

Do you have it in your system or profile paths?
